_wandb:
    value:
        cli_version: 0.21.0
        e:
            vjxohmfkfairg8v4ab225pvq8w0wtiyk:
                args:
                    - --data
                    - data
                    - --checkpoint
                    - sfm_net.pth
                    - --name
                    - kikai
                    - --batch_size
                    - "1"
                    - --num_workers
                    - "0"
                    - --subsampled_sequence_length
                    - "2"
                    - --neighbor_range
                    - "0"
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "158635864064"
                email: linfederico2004@gmail.com
                executable: /home/fedelino/miniconda3/bin/python
                git:
                    commit: 48c64f8efd54a54318efcebfeaae16df047a5c90
                    remote: https://github.com/Fedelino/Kikai.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-38a66841-9841-64c0-63b0-f38d70fbb717
                host: Fedelino
                memory:
                    total: "8328019968"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: -m sfm.train_sfm
                python: CPython 3.13.5
                root: /home/fedelino/k/Kikai
                startedAt: "2025-08-11T07:27:30.200931Z"
                writerId: vjxohmfkfairg8v4ab225pvq8w0wtiyk
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
                - 74
            "2":
                - 1
                - 41
                - 49
                - 63
                - 74
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
accumulate_steps:
    value: 1
batch_size:
    value: 1
checkpoint:
    value: sfm_net.pth
data:
    value: data
epochs:
    value: 100
geometric_consistency_loss_weight:
    value: 0.5
intrinsics_file:
    value: example_inputs/intrinsics.json
l2_pose_reg_weight:
    value: 0
long_sequence_length:
    value: 2
lr:
    value: 0.0001
name:
    value: kikai
neighbor_range:
    value: 0
num_workers:
    value: 0
padding_mode:
    value: zeros
photometric_loss_weight:
    value: 1
seed:
    value: 1
smoothness_loss_weight:
    value: 0.1
subsampled_sequence_length:
    value: 2
with_auto_mask:
    value: false
with_mask:
    value: false
with_replacement:
    value: false
with_ssim:
    value: false
